import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.red-by-sfr.fr/');
  await page.getByRole('button', { name: 'Tout refuser' }).click();
  await page.getByTitle('Forfaits mobile').click();
  await page.locator('#datanat0str').getByText('1Go').click();
  await expect(page.getByText('1,99', { exact: true })).toBeVisible();
  await page.locator('#datanat1str').click();
  await expect(page.getByText('6,99', { exact: true })).toBeVisible();
  await page.locator('#datanat2str').click();
  await expect(page.getByText('9,99', { exact: true })).toBeVisible();
  await page.locator('#datanat3str').click();
  await expect(page.getByText('12,99', { exact: true })).toBeVisible();
  await page.locator('#datanat4str').getByText('350Go 5G').click();
  await expect(page.getByText('19,99', { exact: true })).toBeVisible();
  await page.locator('#table-t1').click();
  await expect(page.getByLabel('Quelles sont les').getByText('1Go', { exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Non Inclus' }).first()).toBeVisible();
  await expect(page.getByText('1,99€/mois')).toBeVisible();
  await expect(page.getByLabel('Quelles sont les').getByText('10Go', { exact: true })).toBeVisible();
  await expect(page.locator('td:nth-child(3) > .cross')).toBeVisible();
  await expect(page.getByText('6,99€/mois')).toBeVisible();
  await expect(page.getByLabel('Quelles sont les').getByText('150Go 5G')).toBeVisible();
  await expect(page.locator('tr:nth-child(4) > td:nth-child(4) > .checked')).toBeVisible();
  await expect(page.getByText('9,99€/mois', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Quelles sont les').getByText('250Go 5G')).toBeVisible();
  await expect(page.locator('tr:nth-child(4) > td:nth-child(5) > .checked')).toBeVisible();
  await expect(page.getByText('12,99€/mois')).toBeVisible();
  await expect(page.getByLabel('Quelles sont les').getByText('350Go 5G')).toBeVisible();
  await expect(page.locator('tr:nth-child(4) > td:nth-child(6) > .checked')).toBeVisible();
  await expect(page.getByText('19,99€/mois')).toBeVisible();
  await page.getByRole('heading', { name: 'Mentions légales' }).click();
  await expect(page.getByRole('heading', { name: 'Forfait 1Go' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Forfait 10Go' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Forfait 150Go 5G' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Forfait 250Go 5G' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Forfait 350Go 5G', exact: true })).toBeVisible();
  await page.getByText('Ne pas ajouter de téléphone').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Fiche d\'Information' }).click();
  const page1 = await page1Promise;
});